server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirect frontend API calls to the backend container
    location /api/v1/ {
        proxy_pass http://htlkrems-predict-backend:8000;
    }
}